package org.libjpegturbo.turbojpeg.bridj;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("turbojpeg")
public class TJRegion extends StructObject {
    static {
        BridJ.register();
    }

    /**
     * The left boundary of the cropping region. This must be evenly divisible<br>
     * by the MCU block width (see #tjMCUWidth.)
     */
    @Field(0)
    public int x() {
        return this.io.getIntField(this, 0);
    }

    /**
     * The left boundary of the cropping region. This must be evenly divisible<br>
     * by the MCU block width (see #tjMCUWidth.)
     */
    @Field(0)
    public TJRegion x(int x) {
        this.io.setIntField(this, 0, x);
        return this;
    }

    /**
     * The upper boundary of the cropping region. This must be evenly divisible<br>
     * by the MCU block height (see #tjMCUHeight.)
     */
    @Field(1)
    public int y() {
        return this.io.getIntField(this, 1);
    }

    /**
     * The upper boundary of the cropping region. This must be evenly divisible<br>
     * by the MCU block height (see #tjMCUHeight.)
     */
    @Field(1)
    public TJRegion y(int y) {
        this.io.setIntField(this, 1, y);
        return this;
    }

    /**
     * The width of the cropping region. Setting this to 0 is the equivalent of<br>
     * setting it to the width of the source JPEG image - x.
     */
    @Field(2)
    public int w() {
        return this.io.getIntField(this, 2);
    }

    /**
     * The width of the cropping region. Setting this to 0 is the equivalent of<br>
     * setting it to the width of the source JPEG image - x.
     */
    @Field(2)
    public TJRegion w(int w) {
        this.io.setIntField(this, 2, w);
        return this;
    }

    /**
     * The height of the cropping region. Setting this to 0 is the equivalent of<br>
     * setting it to the height of the source JPEG image - y.
     */
    @Field(3)
    public int h() {
        return this.io.getIntField(this, 3);
    }

    /**
     * The height of the cropping region. Setting this to 0 is the equivalent of<br>
     * setting it to the height of the source JPEG image - y.
     */
    @Field(3)
    public TJRegion h(int h) {
        this.io.setIntField(this, 3, h);
        return this;
    }

    public TJRegion() {
        super();
    }

    public TJRegion(Pointer pointer) {
        super(pointer);
    }
}
