package org.libjpegturbo.turbojpeg.bridj;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("turbojpeg")
public class TJScalingFactor extends StructObject {
    static {
        BridJ.register();
    }

    /** Numerator */
    @Field(0)
    public int num() {
        return this.io.getIntField(this, 0);
    }

    /** Numerator */
    @Field(0)
    public TJScalingFactor num(int num) {
        this.io.setIntField(this, 0, num);
        return this;
    }

    /** Denominator */
    @Field(1)
    public int denom() {
        return this.io.getIntField(this, 1);
    }

    /** Denominator */
    @Field(1)
    public TJScalingFactor denom(int denom) {
        this.io.setIntField(this, 1, denom);
        return this;
    }

    public TJScalingFactor() {
        super();
    }

    public TJScalingFactor(Pointer pointer) {
        super(pointer);
    }
}
